services:
  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"
  api:
    container_name: api
    build: ./backend
    ports:
      - "${API_HOST_PORT}:${API_CONTAINER_PORT}"
    environment:
      - API_CONTAINER_PORT=${API_CONTAINER_PORT}
  db:
    container_name: db
    image: postgres:latest
    restart: always
    ports:
      - "${DB_HOST_PORT}:${DB_CONTAINER_PORT}" # "Host Port: Container Port"
    environment:
      - POSTGRES_USER=${POSTGRES_USER} 
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
  flyway:
    container_name: flyway
    image: flyway/flyway:latest
    command: -locations=filesystem:/flyway/sql -connectRetries=60 migrate
    volumes:
      - $PWD/backend/internal/db:/flyway/sql
    environment:
      - FLYWAY_USER=${POSTGRES_USER}
      - FLYWAY_PASSWORD=${POSTGRES_PASSWORD}
      - FLYWAY_URL=jdbc:postgresql://db:${DB_CONTAINER_PORT}/${DB_NAME}
    depends_on:
      - db
